version: "3.9"

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "HomeLab"
      LDAP_DOMAIN: "homelab.local"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
      # - ../ldap/ldif/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    ports:
      - "6443:443"
    depends_on:
      - openldap

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../jenkins/pipelines:/var/jenkins_home/pipelines
      - ../jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - jenkins_home:/var/jenkins_home
    depends_on:
      - openldap

  webapp:
    build:
      context: ../webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8081:80"

volumes:
  openldap_data:
  openldap_config:
  jenkins_home:
